### ISSUE TITLE
More Documentation Request

### ISSUE THREAD

**Issue by CanyonCasa** [adafruit/Adafruit-QT-Py-RP2040-PCB#2]
Could someone please add to this repo...

1. A schematic PDF for those of us that don't have or use Eagle.
2. A board outline drawing with hole sizes and placements for making symbols for embedded designs.
3. An updated pinout PDF that includes the GPIOxx for each pin.

**Comment by ladyada** [comment]
those are available here!
https://learn.adafruit.com/adafruit-qt-py-2040/downloads
https://learn.adafruit.com/adafruit-qt-py-2040/pinouts

**Comment by CanyonCasa** [comment]
Thanks. Missed that one. Information overload I guess with too many links to follow.
